---
parser: "@typescript-eslint/parser"

env:
  es2021: true
  node: true
  browser: true

extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/recommended"

plugins:
  - prettier
  - "@typescript-eslint"

rules:
  prettier/prettier: warn # Enable prettier.
  # TODO: Re-enable this after dev.
  "@typescript-eslint/no-unused-vars": off

# Ignore irrelevant dirs.
ignorePatterns:
  - node_modules
  - build
